name: CI/CD Pipeline for Docker

on:
  push:
    branches:
      - main  # Trigger workflow only on pushes to the 'main' branch

jobs:

  docker-build:
    runs-on: ubuntu-latest  # Use an Ubuntu environment for the job

    steps:
    # Printing docker creds
    - name: Debug secrets (temporary)
      run: echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}"
    - name: Debug secrets (temporary)
      run: echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}"
      
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build and push Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/ci-cd-demo:latest
